#language: node_js
#node_js: "8"
#os:
#  - linux
#  - osx

matrix:
  include:
    - os: osx
      language: node_js
      node_js: "8"
    - os: linux
      language: node_js
      node_js: "8"
    - os: linux
      language: generic
      services: docker
      env:
        - BUILD_WIN=1
      
script: 
  - |
    if [ "$BUILD_WIN" == "1" ]; then
      docker run --rm \
        --env-file <(env | grep -iE 'DEBUG|NODE_|ELECTRON_|YARN_|NPM_|CI|CIRCLE|TRAVIS|APPVEYOR_|CSC_|_TOKEN|_KEY|AWS_|STRIP|BUILD_') \
        -v ${PWD}:/project \
        -v ~/.cache/electron:/root/.cache/electron \
        -v ~/.cache/electron-builder:/root/.cache/electron-builder \
        electronuserland/builder:wine \
        /bin/bash -c "npm run electron:publish"
    else
      npm run electron:publish
    fi
#script:
#  - npm run electron:publish

cache:
  directories:
    - $HOME/.npm
    - node_modules